# Generated by Django 4.2.1 on 2023-05-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_gender_choosed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='contries',
            new_name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_app.cities'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_app.countries'),
        ),
    ]
